project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"

website:
  title: "Nano Diffusion"
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
    tools:
      - icon: github
        href: https://github.com/kungfuai/nano-diffusion.git
        text: GitHub

  sidebar:
    - contents:
      - section: "Generating a 2D Point Cloud"
        contents:
          - section: "Diffusion"
            contents:
              - href: "1_1_Diffusion 2D Toy.ipynb"
              - href: "1_1_a_refactor.ipynb"
              - href: "1_1_b_Diffusion_2D_hyperparams.ipynb"
          - section: "Flow Matching"
            contents:
              - href: "1_2_Flow Matching 2D Toy.ipynb"
      - text: "---"
      - section: "Generating Animal Face Images"
        contents:
          - href: "2_1_diffusion_afhq.ipynb"
          - href: "2_1_a_move_off_notebook.qmd"
          - href: "2_2_fid.ipynb"
      - text: "---"
      - section: "Transformers as Denoising Mdels"
        contents:
          - href: "3_1_dit.qmd"
      - text: "---"
      - section: "Text Conditioning"
        contents:
          - href: "4_1_text_conditioning.ipynb"
          - href: "4_1a_generate.ipynb"
      - text: "---"
      - section: "Additional resources"
        contents:
          - href: "slurm.qmd"
format:
  html:
    toc: true
    theme: cosmo
    # theme: readable
    # theme: flatly
    # theme: litera
    highlight: github
    # css: styles.css