project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"

website:
  title: "Nano Diffusion"
  description: "Tutorials and practical recipes on how to build diffusion and flow matching models."
  image: "assets/learned_denoising_vector_field.gif"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
    tools:
      - icon: github
        href: https://github.com/kungfuai/nano-diffusion.git
        text: GitHub

  sidebar:
    - contents:
      - href: "visual_story.qmd"
      - text: "---"
      - section: "Generating a 2D Point Cloud"
        contents:
          - section: "Diffusion"
            contents:
              - href: "1_1_Diffusion 2D Toy.ipynb"
              - href: "1_1_a_refactor.ipynb"
              - href: "1_1_b_Diffusion_2D_hyperparams.ipynb"
          - section: "Flow Matching"
            contents:
              - href: "1_2_Flow Matching 2D Toy.ipynb"
      - text: "---"
      - section: "Generating Animal Face Images"
        contents:
          - href: "2_1_diffusion_afhq.ipynb"
          - href: "2_1_a_move_off_notebook.qmd"
          - href: "2_2_fid.ipynb"
      - text: "---"
      - section: "Text Conditioning"
        contents:
          - href: "4_1_text_conditioning_ddpm.ipynb"
          - href: "4_1a_generate_t2i_ddpm.ipynb"
          - href: "4_2_text_conditioning_cfm.ipynb"
          - href: "4_2a_generate_t2i_cfm.ipynb"
      - text: "---"
      - section: "Scaling up: generate bigger and more diverse images"
      #   contents:
      #     - href: "3_1_transformers_make_use_of_more_data_and_is_easier_to_scale.qmd"
          # - href: "latent_space.qmd"
          # - href: "vdm_faster_training_and_sampling.qmd"
          # - href: "accelerator, mixed precision, model compilation"
          # - href: "distributed training"
          # - href: "data recipe"
      - text: "---"
      - section: "Additional resources"
        contents:
          - href: "slurm.qmd"
format:
  html:
    toc: true
    theme: cosmo
    # theme: readable
    # theme: flatly
    # theme: litera
    highlight: github
    # css: styles.css